algo: "DQN"
env: "ALE/SpaceInvaders-v5"
total_timesteps: 3000000  # Increased for better performance
learning_rate: 0.00025
buffer_size: 500000
learning_starts: 100000
batch_size: 256
exploration_fraction: 0.4
exploration_final_eps: 0.01
train_log_interval: 100

# Network optimization
gamma: 0.99
target_update_interval: 1000
gradient_steps: 4
train_freq: 4
frame_stack: 16

# Preprocessing
scale_rewards: true
normalize_frames: true
terminal_on_life_loss: true

# Game specific settings
difficulty: 0
mode: 0

# Visualization
viz_interval: 25000
video_interval: 100000
video_length: 400
checkpoint_interval: 100000
demo_mode: false

# Model architecture
policy: "CnnPolicy"
features_extractor: "NatureCNN"
features_dim: 512

# Advanced training options
prioritized_replay: true
alpha: 0.6
beta0: 0.4
dueling: true
double_q: true
max_grad_norm: 10 